### ISSUE TITLE
Критерии для ревью

### ISSUE THREAD

**Issue by rzakhar** [Pablo-Escobar11/selenium#1]
Не выполнены следующие критерии

Критерий 1

- __init__.py должен быть в корне, а не в pages
- test_main.py надо переименовать в test_main_page.py
- не хватает pytest.ini 

Критерий 2
- отсутствует test_guest_can_add_product_to_basket
- отсутствует test_guest_can_go_to_login_page_from_product_page
- все четыре теста должны быть помечены как @pytest.mark.need_review
  - test_user_can_add_product_to_basket
  - test_guest_can_add_product_to_basket
  - test_guest_cant_see_product_in_basket_opened_from_product_page
  - test_guest_can_go_to_login_page_from_product_page
  
  Критерий 3
- т.к. нет маркировки, то команда ```pytest -v --tb=line --language=en -m need_review``` не запускает тестов 
- если запускать без маркировки, то много тестов падает, т.к. локатор add_to_basket завязывается на русскую локаль. Лучше написать универсальный локатор 
- тесты, которые падают лучше пометить, как известные падения 

Критерий 4
- в basket_page.py есть два локатора, которые нужно перенести в locators.py

Я еще не выставлял баллы

**Comment by rzakhar** [comment]
Судя по всему, работу уже оценили, т.к. я больше не могу выставить баллы. Надеюсь, мой комментарий помог, удачи!

**Comment by Pablo-Escobar11** [comment]
Чт, 21 сент. 2023 г. в 10:46, Roman Zakharov ***@***.***
помог, спасибо
